### ISSUE TITLE
Initial PayPage Customization: Footer elements can't be customized

### ISSUE THREAD

**Issue by hackmajoris** [unzerdev/php-sdk#20]
Hey guys, 
Looking at your documentation: https://docs.unzer.com/reference/api/, at Initialize pay page for authorization step, it says that it is possible to customize some CSS attributes for the generated page. Some of them are possible to customize, such as header. However, there is no way to customize the footer elements, such as css.backToMerchantLink="color:red".
The style attribute is set, but it's overwritten by jss360 class and the effects are not taken in consideration.

Any tricks on this issue?
![image](https://user-images.githubusercontent.com/3758212/104303240-879cd600-54d2-11eb-9b7c-9f6bd096386a.png)

**Comment by Ryouzanpaku** [comment]
@hackmajoris , we are already planing an update to support PHP8.
